### ISSUE TITLE
Testflight/building on iOS?

### ISSUE THREAD

**Issue by Denperidge** [jackv24/ComicWrap-F#2]
Hello there!
I’ve been looking for an app exactly like you’re developing. Do you have a Testflight, or are there any guidelines on how to build for iOS and perhaps contribute to the project?

**Comment by jackv24** [comment]
Hi, thanks for your interest in the project!

I don't have a TestFlight yet since a few major features are missing, but you can build the app if you'd like. I haven't yet had time to write a full guide for getting started by I did just update the README with some more info in dff65d331859ee7d95932fdb68b78f7147c2fd48

The most major of major features I'll need to add is the ability to refresh and get any new pages, but that'll require some backend work which is a bit harder for others to contribute to.

**Comment by jackv24** [comment]
Hey, I've started the work for a public TestFlight for iOS!

It's not yet ready for a proper public release, but I can add your email to the tester list if you'd like?

**Comment by jackv24** [comment]
Okay my public beta build pipeline is all set up! I haven’t yet put the link up anywhere officially, but here’s a link to join the public TestFlight: https://testflight.apple.com/join/eHMvo9OT
